@include('Layouts.BaseCssLink')
@include('Layouts.SellerNavigation')
@include('Layouts.SellerFooter')
@include('Layouts.BaseJsLink')
@include('Layouts.SellerJsFunctions')
@include('Layouts.BaseJsFunction')

@yield('BaseCssLink')
@yield('SellerNavigation')
@yield('Content')
@yield('SellerFooter')
@yield('BaseJsLinks')
@yield('BaseJsFunction')
@yield('SellerJsFunction')
