@include('Layouts.BaseCssLink')
@include('Layouts.AdminNavigation')
@include('Layouts.AdminFooter')
@include('Layouts.BaseJsLink')
@include('Layouts.BaseJsFunction')
@include('Layouts.AdminJsFunctions')

@yield('BaseCssLink')
</head>
@yield('AdminNavigation')
@yield('Content')
@yield('AdminFooter')
@yield('BaseJsLinks')
@yield('BaseJsFunction')
@yield('AdminJsFunction')
